### ISSUE TITLE
DisqusJS issues

### ISSUE THREAD

**Issue by kidonng** [chawyehsu/chawyehsu.com#183]
![image](https://user-images.githubusercontent.com/44045911/94673180-f2256e00-0348-11eb-881a-47cc45a01600.png)

- Set [`api`](https://github.com/SukkaW/DisqusJS#%E9%85%8D%E7%BD%AE-disqusjs-%E5%8F%82%E6%95%B0) in https://github.com/chawyehsu/chawyehsu.com/blob/main/saber-config.js#L13

  I don't know if it's due to JS engine changes, but DisqusJS's [config merging method](https://github.com/SukkaW/DisqusJS/blob/60a543073734827831871cda709e14aee8afd670/src/disqus.js) is causing [`api`](https://github.com/chawyehsu/chawyehsu.com/blob/e664ae268be292234106bfcc1e9beaddc9df151c/theme/src/components/Disqus.vue#L27) to be `undefined`, so it has to be set explicitly.

- [Configure Disqus Application](https://github.com/SukkaW/DisqusJS#%E9%85%8D%E7%BD%AE-disqus-application)

  I see you have changed the domain recently, this could be another issue.

- (Optional) Set [`adminLabel`](https://github.com/SukkaW/DisqusJS#%E9%85%8D%E7%BD%AE-disqusjs-%E5%8F%82%E6%95%B0) in https://github.com/chawyehsu/chawyehsu.com/blob/main/saber-config.js#L13

  DisqusJS's README says `admin` and `adminLabel` are both needed to show the admin label.

**Comment by chawyehsu** [comment]
Fixed by https://github.com/chawyehsu/chawyehsu.com/commit/7e88c85ea71e5aab0f026355d225d535a8236fa5 and https://github.com/chawyehsu/chawyehsu.com/commit/3cfd7213083b84e3a233001e6a4d7e32a2c8cdb3 .

Thanks, I forgot to update domain on Disqus Application. The default api provided by DisqusJS does not have CORS configured. I deployed it by myself.
